project1/project1/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls')),
]

project1/todo/urls.py
from django.urls import path
from . import views

app_name='todo'

urlpatterns = [
	path('', views.IndexView.as_view(), name='index'),
	path('add-item/', views.addItem, name='addItem' ),
]

project1/todo/models.py
from django.db import models

# Todo Model
class Todo(models.Model):
	todo_text = models.CharField(max_length=200)
	added_date = models.DateTimeField('date added')

	def __str__(self):
		return self.todo_text	

project1/todo/views.py
from django.shortcuts import render
from django.views import generic
from django.utils import timezone
from django.http import HttpResponseRedirect
from django.urls import reverse

from . models import *


# View showing every item in todo list
class IndexView(generic.ListView):
	template_name = 'todo/index.html'
	context_object_name = 'todo_list'

	def get_queryset(self):
		return Todo.objects.all()


def addItem(request):
	time = timezone.now()
	content = request.POST["todo-content"]

	Todo.objects.create(todo_text=content, added_date=time)
	return HttpResponseRedirect(reverse('todo:index'))

project1/todo/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>To Do App</title>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</head>

<body>
	<nav class="navbar navbar-dark bg-dark">
		<a class="navbar-brand" href="#">To Do App</a>
	</nav>
	<div class="container">
		{% block content %} {% endblock content%}
	</div>
</body>

</html>

project1/todo/templates/todo/index.html
{% extends "base.html" %}

{% block content %}

	<form action="{% url 'todo:addItem' %}" method="post">
		{% csrf_token %}
		<div class="form-group">
			<label for="inputText"></label>
			<input type="text" name="todo-content" id="inputText" placeholder="Add Item" value="" />
			<input class="btn btn-primary" type="submit" value="Add">
		</div>
	</form>

	{% if todo_list %}
		{% for todo in todo_list %}
			<li>{{ todo.todo_text }}</li>
		{% endfor %}
	{% else %}
		No Items added
	{% endif %}

{% endblock content %}